### ISSUE TITLE
Filter the entity list

### ISSUE THREAD

**Issue by eileenmcnaughton** [saurabhbatra96/com.saurabhbatra96.civiimport#2]
It's probably work filtering the entity list by whether the entity has a create action - otherwise you get some invalid entities like 'SurveyRespondant'  - which apart from anything else is a misspelling that has been annoying me for years.

Unfortunately the initial load is already a little slow & I can't think of a more efficient way to do this than to iterate through the actions & find out if they have a create action ('getactions'). Perhaps we should cache the results - e.g like

```
  $globalCache = CRM_Utils_Cache::singleton();
  $result = $globalCache->get($cacheKey);
```

NB I would kind of like to be able to import to the profile.submit method too - but that doesn't have to be in scope

**Comment by saurabhbatra96** [comment]
https://github.com/saurabhbatra96/com.saurabhbatra96.civiimport/commit/2602a339a8d01863bcf291957f32552e377413e2#diff-8dc69944751be892b5da5751b85b3a3dR77 fixes this.

Although TBH did not notice any time difference between a cold call and a cache call.
